### ISSUE TITLE
HttpSendBytes Http Method väärä enum

### ISSUE THREAD

**Issue by PekkaKinnunen** [FrendsPlatform/Frends.Web#51]
When passing the #trigger.data.HttpMethod to the task like below, POST becomes PUT:
Enum.Parse(typeof(Frends.Web.Method), #trigger.data.HttpMethod.ToUpper())

How to replicate: 
Make a process with HTTP trigger.
Set HttpSendBytes -task
Set the above code to the Method -field.
Save and activate.
Send POST -request to the process.
Check which Method is actually used in HttpSendBytes.

**Comment by PekkaKinnunen** [comment]
The same method mismatch applies also to HttpSendAndReceiveBytes -task.

PUT becomes PATCH, POST becomes PUT etc.

**Comment by Svenskapojkarna** [comment]
Both SendBytes and SendAndReceiveBytes use SendMethod-enum in the method, not Method.
![image](https://github.com/FrendsPlatform/Frends.Web/assets/36008914/c781af35-023a-4ea7-9964-213a8ac4021e)
https://github.com/FrendsPlatform/Frends.Web/blob/master/Frends.Web/Web.cs#L36
The expression above return enum 2 (POST) from enum Method. In SendMehtod-enum, enum 2 is PUT. Hence, PUT is used instead of POST. Using Frends.Web.SendMehtod fixes the issue.
